site_name: Citizen Clinic Resources (Beta)
site_url: 'https://cltc-berkeley.github.io/resources-beta'
docs_dir: markdown/
site_dir: docs/

repo_name: 'cltc-berkeley/resources-beta'
repo_url: 'https://github.com/cltc-berkeley/resources-beta'
edit_uri: '/cltc-berkeley/resources-beta/tree/master/markdown'

nav:
    - Home: index.md
    - Low-Risk Organization Guide:
        - Introduction: LRO/0-Introduction and TOC (README).md
        - Why do Low-Risk Organizations Need Cybersecurity?: LRO/1-Why do Low-Risk Organizations Need Cybersecurity.md
        - Common Cybersecurity Controls: LRO/2-Common Cybersecurity Controls.md
        - Additional Cybersecurity Best Practices: LRO/3-Additional Cybersecurity Best Practices.md
        - Appendix A - Building a Security Policy for Your Organization: LRO/4-Appendix A Building a Security Policy.md
        - Appendix B - Implementation Guidance: LRO/5-Appendix B Implementation Guidance.md
        - Appendix C - Moving Beyond the Baseline: LRO/6-Appendix C Moving Beyond the Baseline.md
    - Phishing:
        - Setting up GoPhish on AWS: phishing/d1.md
        - Using Gophish: phishing/d2.md
    - Test:
        - Staff:
            - Steve: placeholder.md
        - Students:
            - Raj: raj.md

theme:
  name: material
  custom_dir: clinic_theme
  logo: 'images/logo.png'
  favicon: 'assets/images/favicon.png'
  feature:
    tabs: true
  palette:
    primary: 'white'
    accent: 'indigo'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  next_previous: true

markdown_extensions:
  - footnotes
  - pymdownx.magiclink
