site_name: Citizen Clinic Resources (Beta)
docs_dir: markdown/
site_dir: docs/

repo_name: 'cltc-berkeley/resources-beta'
repo_url: 'https://github.com/cltc-berkeley/resources-beta'
edit_uri: '/cltc-berkeley/resources-beta/tree/master/markdown'

nav:
    - Home: index.md
    - Phishing:
        - Setting up GoPhish on AWS: phishing/d1.md
        - Using Gophish: phishing/d2.md
    - LRO:
        - Need for Cybersecurity: LRO/0-Introduction and TOC (README).md
        - Common Cybersecurity Controls: LRO/2-Common Cybersecurity Controls.md
    - Test:
        - Staff:
            - Steve: placeholder.md
        - Students:
            - Raj: raj.md

theme:
  name: material
  custom_dir: clinic_theme
  logo: 'images/logo.png'
  favicon: 'assets/images/favicon.png'
  feature:
    tabs: true
  palette:
    primary: 'white'
    accent: 'indigo'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  next_previous: true

  markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
