site_name: Beta Resources
docs_dir: markdown/
site_dir: docs/

nav:
    - Home: index.md
    - Phishing:
        - Setting up GoPhish on AWS: phishing/d1.md
        - Using Gophish: phishing/d2.md
    - LRO:
        - Need for Cybersecurity: LRO/0-Introduction and TOC (README).md
        - Common Cybersecurity Controls: LRO/2-Common Cybersecurity Controls.md
    - Test:
        - Staff:
            - Steve: placeholder.md
        - Students:
            - Raj: raj.md

theme:
  name: material
  custom_dir: clinic_theme
  logo: 'images/logo.png'
  favicon: 'images/favicon.png'
  palette:
    primary: 'blue grey'
    accent: 'indigo'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  next_previous: true
